sudo: required

services:
  - docker

before_install:
  - docker build -t wrcs505/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run wrcs505/react-test npm test -- --coverage

after_success:
 - docker build -t wrcs505/multi-client ./client
 - docker build -t wrcs505/multi-nginx ./nginx
 - docker build -t wrcs505/multi-server ./server
 - docker build -t wrcs505/multi-worker ./worker
 # Login to Docker CLI
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 # Take images and push to Docker Hub
 - docker push wrcs505/multi-client
 - docker push wrcs505/multi-nginx
 - docker push wrcs505/multi-server
 - docker push wrcs505/multi-worker



 deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-820977586074
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
