# Specify base image

FROM node:alpine

WORKDIR '/app'

# Install dependencies, configure for dev

COPY ./package.json ./
RUN npm install

# Copy app files from local to container
COPY . .

# Default command

CMD ["npm", "run", "dev"]
